# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_encrypt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Encrypt(object):
    def setupUi(self, Encrypt):
        Encrypt.setObjectName("Encrypt")
        Encrypt.resize(800, 600)
        self.gridLayout_4 = QtWidgets.QGridLayout(Encrypt)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.TitleLabel = TitleLabel(Encrypt)
        self.TitleLabel.setObjectName("TitleLabel")
        self.gridLayout_4.addWidget(self.TitleLabel, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.SubtitleLabel_2 = SubtitleLabel(Encrypt)
        self.SubtitleLabel_2.setObjectName("SubtitleLabel_2")
        self.gridLayout_3.addWidget(self.SubtitleLabel_2, 0, 1, 1, 1)
        self.SubtitleLabel = SubtitleLabel(Encrypt)
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.gridLayout_3.addWidget(self.SubtitleLabel, 0, 0, 1, 1)
        self.plainTextEdit_plain = PlainTextEdit(Encrypt)
        self.plainTextEdit_plain.setObjectName("plainTextEdit_plain")
        self.gridLayout_3.addWidget(self.plainTextEdit_plain, 1, 0, 1, 1)
        self.plainTextEdit_cipher = PlainTextEdit(Encrypt)
        self.plainTextEdit_cipher.setReadOnly(True)
        self.plainTextEdit_cipher.setObjectName("plainTextEdit_cipher")
        self.gridLayout_3.addWidget(self.plainTextEdit_cipher, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.BodyLabel_2 = BodyLabel(Encrypt)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.gridLayout_2.addWidget(self.BodyLabel_2, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 1)
        self.bodyLabel_density = BodyLabel(Encrypt)
        self.bodyLabel_density.setObjectName("bodyLabel_density")
        self.gridLayout_2.addWidget(self.bodyLabel_density, 0, 1, 1, 1)
        self.BodyLabel = BodyLabel(Encrypt)
        self.BodyLabel.setObjectName("BodyLabel")
        self.gridLayout_2.addWidget(self.BodyLabel, 0, 0, 1, 1)
        self.BodyLabel_3 = BodyLabel(Encrypt)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.gridLayout_2.addWidget(self.BodyLabel_3, 0, 2, 1, 1)
        self.bodyLabel_offset = BodyLabel(Encrypt)
        self.bodyLabel_offset.setObjectName("bodyLabel_offset")
        self.gridLayout_2.addWidget(self.bodyLabel_offset, 0, 5, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.primaryPushButton_encrypt = PrimaryPushButton(Encrypt)
        self.primaryPushButton_encrypt.setObjectName("primaryPushButton_encrypt")
        self.gridLayout.addWidget(self.primaryPushButton_encrypt, 0, 0, 1, 1)
        self.indeterminateProgressBar = IndeterminateProgressBar(Encrypt)
        self.indeterminateProgressBar.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.indeterminateProgressBar.setObjectName("indeterminateProgressBar")
        self.gridLayout.addWidget(self.indeterminateProgressBar, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 3, 0, 1, 1)

        self.retranslateUi(Encrypt)
        QtCore.QMetaObject.connectSlotsByName(Encrypt)

    def retranslateUi(self, Encrypt):
        _translate = QtCore.QCoreApplication.translate
        Encrypt.setWindowTitle(_translate("Encrypt", "Form"))
        self.TitleLabel.setText(_translate("Encrypt", "加密"))
        self.SubtitleLabel_2.setText(_translate("Encrypt", "密文"))
        self.SubtitleLabel.setText(_translate("Encrypt", "明文"))
        self.BodyLabel_2.setText(_translate("Encrypt", "偏移量"))
        self.bodyLabel_density.setText(_translate("Encrypt", "-"))
        self.BodyLabel.setText(_translate("Encrypt", "明文信息密度"))
        self.BodyLabel_3.setText(_translate("Encrypt", "bit/词"))
        self.bodyLabel_offset.setText(_translate("Encrypt", "-"))
        self.primaryPushButton_encrypt.setText(_translate("Encrypt", "加密"))
from qfluentwidgets import BodyLabel, IndeterminateProgressBar, PlainTextEdit, PrimaryPushButton, SubtitleLabel, TitleLabel
