# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(800, 600)
        self.gridLayout_2 = QtWidgets.QGridLayout(Settings)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.TitleLabel = TitleLabel(Settings)
        self.TitleLabel.setObjectName("TitleLabel")
        self.gridLayout_2.addWidget(self.TitleLabel, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(779, 431, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.BodyLabel_2 = BodyLabel(Settings)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.gridLayout.addWidget(self.BodyLabel_2, 1, 0, 1, 1)
        self.doubleSpinBox_density_level = DoubleSpinBox(Settings)
        self.doubleSpinBox_density_level.setProperty("value", 15.0)
        self.doubleSpinBox_density_level.setObjectName("doubleSpinBox_density_level")
        self.gridLayout.addWidget(self.doubleSpinBox_density_level, 2, 1, 1, 1)
        self.BodyLabel_4 = BodyLabel(Settings)
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.gridLayout.addWidget(self.BodyLabel_4, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 3, 1, 1)
        self.BodyLabel = BodyLabel(Settings)
        self.BodyLabel.setObjectName("BodyLabel")
        self.gridLayout.addWidget(self.BodyLabel, 0, 0, 1, 1)
        self.BodyLabel_6 = BodyLabel(Settings)
        self.BodyLabel_6.setProperty("lightColor", QtGui.QColor(255, 0, 0))
        self.BodyLabel_6.setProperty("darkColor", QtGui.QColor(255, 0, 0))
        self.BodyLabel_6.setObjectName("BodyLabel_6")
        self.gridLayout.addWidget(self.BodyLabel_6, 2, 5, 1, 1)
        self.BodyLabel_3 = BodyLabel(Settings)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.gridLayout.addWidget(self.BodyLabel_3, 2, 0, 1, 1)
        self.BodyLabel_5 = BodyLabel(Settings)
        self.BodyLabel_5.setProperty("lightColor", QtGui.QColor(0, 255, 0))
        self.BodyLabel_5.setProperty("darkColor", QtGui.QColor(0, 255, 0))
        self.BodyLabel_5.setObjectName("BodyLabel_5")
        self.gridLayout.addWidget(self.BodyLabel_5, 2, 4, 1, 1)
        self.bodyLabel_seed_int = BodyLabel(Settings)
        self.bodyLabel_seed_int.setObjectName("bodyLabel_seed_int")
        self.gridLayout.addWidget(self.bodyLabel_seed_int, 1, 1, 1, 5)
        self.lineEdit_seed_str = LineEdit(Settings)
        self.lineEdit_seed_str.setObjectName("lineEdit_seed_str")
        self.gridLayout.addWidget(self.lineEdit_seed_str, 0, 1, 1, 5)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Form"))
        self.TitleLabel.setText(_translate("Settings", "设置"))
        self.BodyLabel_2.setText(_translate("Settings", "种子（整数）"))
        self.BodyLabel_4.setText(_translate("Settings", "bit/词"))
        self.BodyLabel.setText(_translate("Settings", "种子（字符串）"))
        self.BodyLabel_6.setText(_translate("Settings", "高于该值视为无效信息"))
        self.BodyLabel_3.setText(_translate("Settings", "信息密度判定线"))
        self.BodyLabel_5.setText(_translate("Settings", "低于该值视为有效信息"))
        self.bodyLabel_seed_int.setText(_translate("Settings", "-"))
from qfluentwidgets import BodyLabel, DoubleSpinBox, LineEdit, TitleLabel
