name: 打包发疯文学加密

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本'
        required: true
      windows-console-mode:
        description: 'windows-console-mode'
        required: true
        default: disable

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: 签出存储库
        uses: actions/checkout@v4

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: 安装依赖项
        run: |
          pip install -r requirements.txt

      - name: 构建可执行文件
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: src/main.py
          standalone: true
          output-file: CrazyLiteratureEncryption
          product-name: 发疯文学加密
          file-description: 发疯文学加密
          file-version: ${{ github.event.inputs.version }}
          product-version: ${{ github.event.inputs.version }}
          copyright: "Copyright MC着火的冰块. All rights reserved."
          include-package-data: jieba
          enable-plugins: pyqt5
          windows-console-mode: ${{ github.event.inputs.windows-console-mode }}
          macos-create-app-bundle: true

      - name: 上传工件
        uses: actions/upload-artifact@v4
        with:
          name: CrazyLiteratureEncryption-v${{ github.event.inputs.version }}-${{ runner.os }}
          path: |
            build/main.dist/*
